{{- if not .Values.csi.enable }}

{{- if .Values.rbacEnabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "storageos.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "storageos.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "storageos.fullname" . }}
{{- end -}}

{{- end }}

---

{{- if .Values.podSecurityPolicy.enabled }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "storageos.fullname" . }}-psp-user
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
   apiGroup: rbac.authorization.k8s.io
   kind: ClusterRole
   name: {{ template "storageos.fullname" . }}-psp-user
subjects:
  {{- if .Values.csi.enable }}
  - kind: ServiceAccount
    name: {{ template "storageos.fullname" . }}-daemonset-sa
    namespace: {{ .Release.Namespace }}
  - kind: ServiceAccount
    name: {{ template "storageos.fullname" . }}-statefulset-sa
    namespace: {{ .Release.Namespace }}
  {{- else }}
  - kind: ServiceAccount
    name: {{ template "storageos.fullname" . }}
    namespace: {{ .Release.Namespace }}
  {{- end }}

{{- end }}
