{{- if not .Values.csi.enable }}

apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.name }}
  labels:
    app: {{ template "storageos.name" . }}
    chart: {{ template "storageos.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
provisioner: kubernetes.io/storageos
parameters:
  pool: {{ .Values.storageclass.pool }}
  description: Kubernetes volume
  fsType: {{ .Values.storageclass.fsType }}
  adminSecretNamespace: {{ .Release.Namespace }}
  adminSecretName: {{ .Values.api.secretName }}

{{- end }}
