apiVersion: v1
appVersion: "v2.1.0"
description: Cloud Native storage for containers
name: storageos-operator
version: 0.3.0
tillerVersion: ">=2.10.0"
keywords:
- storage
- block-storage
- volume
- operator
home: https://storageos.com
icon: https://../storageos.svg
sources:
- https://github.com/storageos
maintainers:
- name: croomes
  email: simon.croome@storageos.com
- name: darkowlzz
  email: sunny.gogoi@storageos.com
