name: storageos
version: 1.0.8
description: Converged storage for containers
appVersion: 1.2.0
apiVersion: v1
keywords:
- storage
- block-storage
- volume
home: https://storageos.com
icon: https://storageos.com/wp-content/themes/storageOS/images/logo.svg
sources:
- https://github.com/storageos
maintainers:
- name: croomes
  email: simon.croome@storageos.com
- name: darkowlzz
  email: sunny.gogoi@storageos.com
