apiVersion: v1
appVersion: "1.3.0"
description: A StorageOS Cluster Operator chart for Kubernetes
name: storageoscluster-operator
version: 1.1.4
keywords:
- storage
- block-storage
- volume
- operator
home: https://storageos.com
icon: https://storageos.com/wp-content/themes/storageOS/images/logo.svg
sources:
- https://github.com/storageos
deprecated: true
