apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "storageoscluster-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "storageoscluster-operator.name" . }}
    chart: {{ template "storageoscluster-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "storageoscluster-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "storageoscluster-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "storageoscluster-operator.serviceAccountName" . }}
      containers:
        - name: storageoscluster-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - cluster-operator
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "cluster-operator"
